# Generated by Django 2.0.2 on 2018-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(to='invitations.Invitation'),
        ),
    ]
