# Generated by Django 2.0.2 on 2018-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180428_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_week',
            field=models.CharField(default='2018-W17', help_text='The week the project ends', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_week',
            field=models.CharField(default='2018-W12', help_text='The week the project starts', max_length=8),
            preserve_default=False,
        ),
    ]
