# Generated by Django 2.0.2 on 2018-04-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180428_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start',
        ),
    ]
