# Generated by Django 2.0.2 on 2018-04-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billable',
            field=models.BooleanField(default=True, help_text='Only billable projects can be invoiced'),
        ),
    ]
