# Generated by Django 2.0.2 on 2018-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_billable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('colour', models.CharField(choices=[('Grey', 'grey'), ('Blue', 'blue'), ('Green', 'green'), ('Red', 'red'), ('Orange', 'orange')], default='Grey', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-colour'],
            },
        ),
    ]
