# Generated by Django 2.0.2 on 2018-05-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectStatus', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
