# Generated by Django 2.0.2 on 2018-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='colour',
            field=models.CharField(choices=[('Blue', 'Blue = Closed'), ('Green', 'Green = Active'), ('Red', 'Red = On hold')], default='Grey', max_length=10),
        ),
    ]
