# Generated by Django 2.0.2 on 2018-05-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180524_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='On Hold', max_length=10),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
