# Generated by Django 2.0.2 on 2018-06-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180609_2150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_historicalproject_historicaltask_historicalteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoices.Customer'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
