# Generated by Django 2.0.2 on 2018-06-25 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('C', 'Cloud'), ('M', 'Mobile'), ('D', 'Desktop'), ('T', 'Tablet'), ('H', 'Hybrid')], default='C', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='cost',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='cost_type',
            field=models.CharField(choices=[('1', 'One time payment'), ('M', 'Monthly'), ('Y', 'Annually')], default='Y', max_length=1, verbose_name='Renewal'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='purpose',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.URLField(),
        ),
    ]
