# Generated by Django 2.0.2 on 2018-06-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20180625_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_in_confidence', models.BooleanField(default=False)),
                ('staff_in_confidence', models.BooleanField(default=False)),
                ('commercial_in_confidence', models.BooleanField(default=False)),
                ('statistical_unclassified', models.BooleanField(default=False)),
                ('unclassified', models.BooleanField(default=False)),
                ('special_handling_sensitive_patient', models.BooleanField(default=False)),
                ('special_handling_sensitive_disease', models.BooleanField(default=False)),
                ('special_handling_sensitive_abuse', models.BooleanField(default=False)),
                ('special_handling_sensitive_other', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Application', unique=True)),
            ],
        ),
    ]
