# Generated by Django 2.0.2 on 2018-06-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_informationclassification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationclassification',
            name='id',
        ),
        migrations.AlterField(
            model_name='informationclassification',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assessment.Application'),
        ),
    ]
