# Generated by Django 2.0.2 on 2018-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20180626_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudICTBriefCloudRiskAssessment',
            fields=[
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assessment.Application')),
                ('termsconditions_URL', models.URLField(help_text='Please supply the applications terms and conditions from the vendors website.')),
                ('privacypolicy_URL', models.URLField(help_text='Please supply the applications privacy policy from the vendors website.')),
                ('dhb_record_volume', models.CharField(choices=[('TENS', '10s'), ('HUNDREDS', '100s'), ('THOUSANDS', '1,000s'), ('TENTHOUSANDS', '10,000s'), ('HUNDREDTHOUSANDS', '100,000s')], default='TENS', help_text='The volume of records we expect to store in the cloud service on an annual basis', max_length=15)),
                ('dhb_downtime_before_critical', models.CharField(choices=[('H', 'Hours'), ('D', 'Days'), ('M', 'Months'), ('I', 'Indefinitely')], default='H', help_text='We can be without this cloud service before our service can no longer function properly for', max_length=1)),
                ('dhb_log_data_changes', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='cloudquestionnaire',
            name='alteration_risk',
            field=models.BooleanField(default=False, help_text='No person or organisation will be harmed if the information is altered by mistake or intentionally by a wrongdoer.', verbose_name='Information Alteration Risk'),
        ),
        migrations.AlterField(
            model_name='cloudquestionnaire',
            name='continuity_risk',
            field=models.BooleanField(default=False, help_text='We will be able to carry on our activities if the service is disrupted or is unavailable for an extended.', verbose_name='Business Continuity Risk'),
        ),
        migrations.AlterField(
            model_name='cloudquestionnaire',
            name='disclosure_risk',
            field=models.BooleanField(default=False, help_text='The information is publicly available or it can be de-identified so that its release into the public domain would not compromise our obligations to a person or an organisation.', verbose_name='Information Disclosure Risk'),
        ),
        migrations.AlterField(
            model_name='cloudquestionnaire',
            name='loss_risk',
            field=models.BooleanField(default=False, help_text='No person or orginastion will be harmed if the information is lost by the cloud provider; OR we can easily maintain a local copy of the information.', verbose_name='Information Loss Risk'),
        ),
    ]
