# Generated by Django 2.0.2 on 2018-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='trading_name',
            field=models.CharField(help_text='Enter the trading name of the customer', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='trading_name',
            field=models.CharField(db_index=True, help_text='Enter the trading name of the customer', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalinvoicesettings',
            name='trading_name',
            field=models.CharField(db_index=True, help_text='Your trading name', max_length=120),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='trading_name',
            field=models.CharField(help_text='Your trading name', max_length=120, unique=True),
        ),
    ]
