# Generated by Django 2.0.2 on 2018-04-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvoiceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=240)),
                ('street_address', models.CharField(max_length=240)),
                ('suburb', models.CharField(max_length=240)),
                ('city_town', models.CharField(max_length=240)),
                ('postcode', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=240)),
                ('logo', models.CharField(max_length=240)),
                ('gst_rate', models.CharField(max_length=240)),
                ('gst_number', models.CharField(max_length=240)),
                ('payment_terms', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
