# Generated by Django 2.0.2 on 2018-06-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvoiceprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInvoiceProfile',
        ),
    ]
