# Generated by Django 2.0.2 on 2018-04-27 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTimesheet',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('week_start', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekTimesheetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tue', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fri', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sun', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
                ('timesheet', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='timesheets.WeekTimesheet')),
            ],
        ),
    ]
