# Generated by Django 2.0.2 on 2018-04-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
