# Generated by Django 2.0.2 on 2018-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weektimesheet',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='weektimesheet',
            name='status',
            field=models.CharField(choices=[('New', 'New timesheet'), ('Submitted', 'Submitted awaiting approval'), ('Approved', 'Approved'), ('Resubmitted', 'Resubmitted awaiting approval'), ('Invoiced', 'Customer has been invoiced'), ('Rework', 'Rework required'), ('Closed', 'Closed no longer accepts new data')], default='New', max_length=20),
        ),
    ]
