# Generated by Django 2.0.2 on 2018-05-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_auto_20180524_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='weektimesheetline',
            name='status',
            field=models.CharField(choices=[('New', 'New timesheet'), ('Submitted', 'Submitted awaiting approval'), ('Approved', 'Approved'), ('Resubmitted', 'Resubmitted awaiting approval'), ('Invoiced', 'Customer has been invoiced'), ('Rework', 'Rework required'), ('Closed', 'Closed no longer accepts new data')], default='New', max_length=20),
        ),
    ]
