# Generated by Django 2.0.2 on 2018-05-28 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_historicalproject_historicaltask_historicalteam'),
        ('timesheets', '0003_weektimesheetline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeekTimesheet',
            fields=[
                ('name', models.CharField(db_index=True, max_length=40)),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('New', 'New timesheet'), ('Submitted', 'Submitted awaiting approval'), ('Approved', 'Approved'), ('Resubmitted', 'Resubmitted awaiting approval'), ('Invoiced', 'Customer has been invoiced'), ('Rework', 'Rework required'), ('Closed', 'Closed no longer accepts new data')], default='New', max_length=20)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical week timesheet',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeekTimesheetLine',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mon', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tue', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fri', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sun', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('New', 'New timesheet'), ('Submitted', 'Submitted awaiting approval'), ('Approved', 'Approved'), ('Resubmitted', 'Resubmitted awaiting approval'), ('Invoiced', 'Customer has been invoiced'), ('Rework', 'Rework required'), ('Closed', 'Closed no longer accepts new data')], default='New', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Project')),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Task')),
                ('timesheet', models.ForeignKey(blank=True, db_column='name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timesheets.WeekTimesheet')),
            ],
            options={
                'verbose_name': 'historical week timesheet line',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
