# Generated by Django 2.0.2 on 2018-04-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20180419_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weektimesheet',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
