# Generated by Django 2.0.2 on 2018-06-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_historicalweektimesheetlineapprovals_weektimesheetlineapprovals'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweektimesheetlineapprovals',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weektimesheetlineapprovals',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
